[[PackageOverrides]]
name = "github.com/asaskevich/govalidator"
version = "0.0.0-20230301143203-a9d515a09cc2"
ecosystem = "Go"
license.override = ["MIT"]

[[PackageOverrides]]
name = "github.com/distribution/reference"
version = "0.6.0"
ecosystem = "Go"
license.override = ["Apache-2.0"]

