name: Build and Test
on:
  push:
    branches:
    - "main"
    - "release/v*"
    paths-ignore:
    - "**/*.png"
  pull_request:
    branches:
    - "main"
    - "release/v*"
    paths-ignore:
    - "**/*.png"

permissions:
  contents: read

jobs:
  # Check if there are changes that require running the test jobs
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      run_test_workflow: ${{ steps.check-changes.outputs.run_test_workflow }}
    steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
      id: check-changes
      # A dependent job will be automatically skipped if its parent job is skipped.
      # So we skip this step in pull_request event if the changes are not relevant.
      if: github.event_name == 'pull_request'
      with:
        filters: |
          run_test_workflow:
            - "!?(.github|site|release-notes)/**"
            - ".github/workflows/build_and_test.yaml"

  lint:
    runs-on: ubuntu-22.04
    steps:
    - run: exit 0

  build:
    runs-on: ubuntu-latest
    needs: [changes, lint]
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.run_test_workflow == 'true' }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      # For main branch builds, we need to fetch tags so go binary will be built with
      # the recent vX.Y.Z-rc.0 tag, which helps avoid false positives in vulnerability scans.
      # `fetch-tags: true` doesn't work: https://github.com/actions/checkout/issues/1471
      # As a workaround `filter: tree:0` is used to create a treeless clone.
      # See:
      # https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
      # https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
      with:
        fetch-depth: ${{ github.ref == 'refs/heads/main' && '0' || '1' }}
        filter: ${{ github.ref == 'refs/heads/main' && 'tree:0' || '' }}
    - uses: ./tools/github-actions/setup-deps

    - name: Build EG Multiarch Binaries
      run: make build-multiarch PLATFORMS="linux_amd64 linux_arm64"

    - name: Upload EG Binaries
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
      with:
        name: envoy-gateway
        path: bin/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - uses: ./tools/github-actions/setup-deps

    - name: Download EG Binaries
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      with:
        name: envoy-gateway
        path: bin/

    - name: Give Privileges To EG Binaries
      run: |
        chmod +x bin/linux/amd64/envoy-gateway
        chmod +x bin/linux/arm64/envoy-gateway

    # build and push image
    - name: Login to DockerHub
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2  # v4.0.0
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Setup Multiarch Environment
      run: make image.multiarch.setup

    - name: Build and Push EG Commit Image
      # tag is set to the short SHA of the commit
      run: make image.push.multiarch PLATFORMS="linux_amd64 linux_arm64" IMAGE=shaharharari/gateway-dev

    - name: Build and Push EG Latest Image
      # tag is set to `latest` when pushing to main branch
      run: make image.push.multiarch TAG=latest PLATFORMS="linux_amd64 linux_arm64" IMAGE=shaharharari/gateway-dev

    - name: Build and Push EG Latest Helm Chart
      # use `0.0.0` as the default latest version.
      # use `Always` image pull policy for latest version.
      run: |
        IMAGE_PULL_POLICY=Always OCI_REGISTRY=oci://docker.io/shaharharari CHART_VERSION=v0.0.0-latest TAG=latest make helm-push
        IMAGE_PULL_POLICY=Always OCI_REGISTRY=oci://docker.io/shaharharari CHART_VERSION=0.0.0-latest TAG=latest make helm-push
