name: trivy

on:
  pull_request:
    branches:
    - "main"
  push:
    branches:
    - "main"
  schedule:
  - cron: '55 17 * * 5'

permissions:
  contents: read

jobs:
  trivy-image-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Trivy Image Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3

      - name: Build an image from Dockerfile
        run: |
          IMAGE=envoy-proxy/gateway-dev TAG=${{ github.sha }} make image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55  # v0.19.0
        with:
          image-ref: envoy-proxy/gateway-dev:${{ github.sha }}
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          severity: CRITICAL,HIGH

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c7f9125735019aa87cfc361530512d50ea439c71  # v3.25.1
        with:
          sarif_file: trivy-results.sarif
